services:

  frinkconv-api:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    ports:
      - ${PORT}:${PORT}
    command: [ "-port", "${PORT:-8080}", "-processes", "${PROCESSES:-4}" ]
