name: Go Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Install frinkconv and deps
      run: |
        sudo apt-get update && sudo apt-get install -y git default-jre rlwrap wget
        git clone https://github.com/seanbreckenridge/frinkconv.git
        cd frinkconv
        ./frinkconv
        sudo cp -frv frinkconv /usr/local/bin
        rm -fr frinkconv
        cd ..

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
